### ISSUE TITLE
Requesting Attachments of Documents

### ISSUE THREAD

**Issue by KARTHICKRK28** [KARTHICKRKO/Ticketbooking_Development#6]
Dear KarthickRKO,

It would be great if the app is capable of attaching the documents as well. Kindly add this feature.

**Comment by KARTHICKRKO** [comment]
Dear RK28,

Thanks for Suggesting this feature. We will add this implementation and let you know.

**Comment by KARTHICKRKO** [comment]
Dear RK28,

Thanks for your valuable suggestion. This feature is going to make our product great
